app/Http/routes.php
<?php


/**
 * WEB ROUTES
 */
Route::group(['middleware' => ['web','ip-lock']], function($request) {

    Route::post('/register', 'Web\AuthController@register');
    Route::get('/register', 'Web\AuthController@registerPage');
    Route::post('/login', 'Web\AuthController@login');
    Route::get('/login', 'Web\AuthController@loginPage');
    Route::get('/logout', 'Auth\AuthController@logout');
    Route::get('login/facebook', 'Web\AuthController@redirectToProvider');
    Route::get('login/facebook/callback', 'Web\AuthController@handleProviderCallback');

    Route::get('/', 'Web\SearchController@explore');
    Route::get('/wanted', 'Web\SearchController@wanted');
    Route::get('/search', 'Web\SearchController@searchRedirect');
    Route::post('/search/filter', 'Web\SearchController@ajax_search');
    Route::get('/search/users/{term}', 'Web\SearchController@searchUsers');
    Route::get('/search/{term}', 'Web\SearchController@search');

    Route::group(['prefix' => 'shoes'], function ($request) {
        Route::post('/load-comments', 'Web\ShoeController@ajaxComments');
        Route::get('/{slug}/edit', 'Web\ShoeController@editShoe');
        Route::post('/{slug}/edit', 'Web\ShoeController@postEditShoe');
        Route::get('/{slug}', 'Web\ShoeController@viewShoe');
    });

    Route::group(['prefix' => 'profile'], function ($request) {
        Route::get('/{slug}', 'Web\ProfileController@index');
        Route::get('/{slug}/listings', 'Web\ProfileController@listings');
        Route::get('/{slug}/likes', 'Web\ProfileController@likes');
        Route::get('/{slug}/reviews', 'Web\ProfileController@reviews');
        Route::get('/{slug}/reviews/sold', 'Web\ProfileController@reviewsSold');
        Route::get('/{slug}/reviews/purchased', 'Web\ProfileController@reviewsPurchased');
        Route::get('/{slug}/followers', 'Web\ProfileController@followers');
        Route::get('/{slug}/following', 'Web\ProfileController@following');
        Route::get('/{slug}/report', 'Web\ProfileController@report');
        Route::post('/follow/{id}', 'Web\ProfileController@ajaxFollow');
    });

    Route::get('faq', 'Web\AboutController@viewFaq');
    Route::post('faq/contact', 'Web\AboutController@postContact');

    //Must be logged in to access
    Route::group(['middleware' => 'auth'], function($request) {
        Route::post('/upload-image', 'Web\AuthController@upload_profile_image');
        Route::get('/notifications', 'Web\NotificationController@view');
        Route::get('/notifications/load-more/{type}', 'Web\NotificationController@ajaxLoad');
        Route::post('/notifications/delete/{id}', 'Web\NotificationController@ajaxDelete');
        Route::post('/notifications/viewed', 'Web\NotificationController@ajaxViewed');

        Route::group(['prefix' => 'payment'], function ($request) {
            Route::get('/edit-bank', 'Web\PaymentController@bankDetails');
            Route::post('/edit-bank', 'Web\PaymentController@postBankDetails');
            Route::get('/shoe/{id}', 'Web\PaymentController@payShoe');
            Route::get('/offer/{id}', 'Web\PaymentController@payOffer');
            Route::post('pay', 'Web\PaymentController@ajaxPay');
            Route::get('/complete/{id}', 'Web\PaymentController@purchaseComplete');
        });

        Route::group(['prefix' => 'account'], function ($request) {
            Route::get('/', 'Web\AccountController@index');
            Route::get('/listings', 'Web\AccountController@listings');
            Route::get('/likes', 'Web\AccountController@likes');
            Route::get('/offers/received', 'Web\AccountController@offersReceived');
            Route::get('/offers/sent', 'Web\AccountController@offersSent');
            Route::post('/offers/{id}/accept', 'Web\AccountController@ajaxAcceptOffer');
            Route::post('/offers/{id}/decline', 'Web\AccountController@ajaxDeclineOffer');
            Route::get('/wanted', 'Web\AccountController@wanted');
            Route::get('/transactions/purchases', 'Web\AccountController@listPurchases');
            Route::get('/transactions/sold', 'Web\AccountController@listSold');
            Route::post('/transactions/review', 'Web\AccountController@postReview');
            Route::post('/transactions/dispute', 'Web\AccountController@postDispute');
            Route::post('/transactions/{id}/dispatch', 'Web\AccountController@ajaxDispatchSold');
            Route::get('/edit', 'Web\AccountController@edit');
            Route::post('/edit', 'Web\AccountController@postEdit');
            Route::post('/edit/image', 'Web\AccountController@postEditPicture');

            Route::get('/complete', 'Web\AccountController@complete');
            Route::post('/complete', 'Web\AccountController@addUsername');
        });

        Route::group(['prefix' => 'upload'], function ($request) {
            Route::get('/shoe', 'Web\ListingController@index');
            Route::post('/shoe', 'Web\ListingController@addShoe');

        });

        Route::group(['prefix' => 'shoes'], function ($request) {
            Route::post('/like/{id}', 'Web\APIController@likeShoe');
            Route::post('/unlike/{id}', 'Web\APIController@unlikeShoe');
            Route::post('/comment', 'Web\ShoeController@ajaxComment');
            Route::post('/delete/{id}', 'Web\ShoeController@ajaxDelete');
            Route::post('/mark-sold/{id}', 'Web\ShoeController@ajaxMarkSold');
            Route::post('/offer/{id}', 'Web\ShoeController@ajaxOffer');
            Route::get('/{slug}/edit', 'Web\ShoeController@editShoe');
        });

    });
});


/**
 * API ENDPOINTS (V1)
 */

Route::group(['prefix' => 'api/v1','middleware' => 'api'], function($request) {
    //Account management
    Route::group(['prefix' => 'auth'], function ($request) {
        Route::post('/login', 'API\V1\AuthController@login');
        Route::post('/login/fb', 'API\V1\AuthController@fbLogin');
        Route::post('/register', 'API\V1\AuthController@register');
        Route::get('/logout', 'API\V1\AuthController@logout');
        Route::post('/reset', 'API\V1\AuthController@reset');
        Route::get('/appdata', 'API\V1\AuthController@appdata');
    });
    
    Route::get('update', 'API\V1\AuthController@update');

    //AUTHENTICATED ROUTES
    Route::group(['middleware' => 'jwt'], function ($request) {

        //Stripe payment
        Route::group(['prefix' => 'payment'], function ($request) {
            Route::get('/source', 'API\V1\PaymentController@getBankAccount');
            Route::post('/source', 'API\V1\PaymentController@saveBankAccount');
            Route::get('/transactions', 'API\V1\PaymentController@listTransactions');
            Route::post('/transfer', 'API\V1\PaymentController@transferToBank');
            if (env('APP_DEBUG')) Route::get('/topup', 'API\V1\PaymentController@topup');
        });

        //Shoes
        Route::group(['prefix' => 'shoes'], function ($request) {
            Route::get('/', 'API\V1\ShoeController@viewAll');
            Route::get('/followed', 'API\V1\ShoeController@feed');
            Route::post('/tailor', 'API\V1\TailoringController@tailoring');
            Route::get('/search', 'API\V1\ShoeController@search');
            Route::post('/like/{shoe_id}', 'API\V1\ShoeController@like');
            Route::post('/unlike/{shoe_id}', 'API\V1\ShoeController@unlike');
            Route::get('/{shoe_id}', 'API\V1\ShoeController@get');
        });
        //users
        Route::group(['prefix' => 'users'], function ($request) {
            Route::get('/', 'API\V1\UserController@getUsers');
            Route::get('/search/{search_term}', 'API\V1\UserController@search');
            Route::get('/search/', 'API\V1\UserController@getUsers');
            Route::get('/rating/{user_id}', 'API\V1\UserController@getUserRating');
            Route::get('/shoes/{user_id}', 'API\V1\UserController@getShoes');
            Route::get('/likes/{user_id}', 'API\V1\UserController@getLikes');
            Route::get('/followers/{user_id}', 'API\V1\UserController@getFollowers');
            Route::get('/following/{user_id}', 'API\V1\UserController@getFollowing');
            Route::get('/reviews-buyer/{user_id}', 'API\V1\UserController@reviewsAsBuyer');
            Route::get('/reviews-seller/{user_id}', 'API\V1\UserController@reviewsAsSeller');
            Route::get('/{id}/', 'API\V1\UserController@getById');
        });

        //Following users
        Route::group(['prefix' => 'follow'], function ($request) {
            Route::post('/{user_id}', 'API\V1\UserController@follow');
            Route::post('remove/{user_id}', 'API\V1\UserController@unfollow');
        });
        //Blocking users
        Route::group(['prefix' => 'block'], function ($request) {
            Route::post('/{user_id}', 'API\V1\UserController@block');
        });
        //Comments
        Route::group(['prefix' => 'comments'], function ($request) {
            Route::get('/get/{shoe_term}', 'API\V1\CommentController@get');
            Route::post('/{shoe_id}', 'API\V1\CommentController@post');
        });
        //Profile
        Route::group(['prefix' => 'profile'], function ($request) {
            Route::get('/', 'API\V1\ProfileController@viewInfo');
            Route::post('', 'API\V1\ProfileController@editProfile');
            Route::get('/listings', 'API\V1\ProfileController@viewShoes');
            Route::get('/wanted', 'API\V1\ProfileController@viewWantedShoes');
            Route::get('/sold', 'API\V1\ProfileController@viewSoldShoes');
            Route::get('/purchased', 'API\V1\ProfileController@viewPurchased');
            Route::get('/reviews-buyer', 'API\V1\ProfileController@reviewsAsBuyer');
            Route::get('/reviews-seller', 'API\V1\ProfileController@reviewsAsSeller');
            Route::get('/followers', 'API\V1\ProfileController@followers');
            Route::get('/following', 'API\V1\ProfileController@following');

app/Dispute.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Dispute extends Model
{
    public function purchase()
    {
        return $this->belongsTo('App\Purchase');
    }

    /**
     * The title (buyer or seller) for the user that disputed the purchase.
     */
    public function getDisputerAttribute()
    {
        if (Auth::user()->id != $this->disputer_id) {
            if ($this->purchase->buyer_id == $this->disputer_id) {
                return 'Buyer';
            } else {
                return 'Seller';
            }
        }

        return '';
    }
}

app/Purchase.php
<?php
/**
 * Created by PhpStorm.
 * User: ed
 * Date: 26/02/16
 * Time: 12:13
 */

namespace App;


use Illuminate\Database\Eloquent\Model;

class Purchase extends Model
{
    protected $with = ['dispute'];
    protected $hidden = ['refunded'];

    function shoe(){
        return $this->belongsTo('App\Shoe')->with('brand_info', 'colors', 'sizes', 'comments', 'commentCount', 'likes', 'images', 'seller','reviewBySeller','reviewByBuyer');
    }

    function user(){
        return $this->belongsTo('App\User', 'buyer_id');
    }

    /**
     * Morph notification type, to a notification.
     */
    public function notification()
    {
        return $this->morphMany('Notification', 'notification');
    }

    /**
     * A dispute about the purchase.
     */
    public function dispute()
    {
        return $this->hasOne('App\Dispute', 'purchase_id', 'id');
    }

    /**
     * The stripe transaction associated with a purchase
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function stripeTransaction()
    {
        return $this->hasOne('App\StripeTransaction');
    }

    /**
     * Human readable status for purchases.
     *
     * @return string
     */
    public function getFormattedStatusAttribute()
    {
        switch ($this->status) {
            case 'pending': return 'Payment pending';
            case 'paid': return 'Not dispatched';
            case 'dispatched': return 'Dispatched';
        }
    }

    public function getFormattedShippingAddressAttribute()
    {
        $parts = [
            $this->ship_address_line1,
            $this->ship_address_line2,
            $this->ship_address_city,
            $this->ship_address_county,
            $this->ship_address_postcode
        ];
        $address = '';

        foreach ($parts as $part) {
            if ($part !== null && $part !== '') {
                $address .= $part . ', ';
            }
        }

        return trim($address, ', ');
    }
}

resources/views/pages/account/header.blade.php
<div class="col-xs-12 no-padding margin-bottom-1 margin-top-1 visible-xs border-bottom"> <a href="{{ url('account/edit') }}" class="btn sole-btn bordered-grey-btn pull-left edit-profile">Edit Profile</a>
    <select id="dynamic_select" dir="rtl" class="filter-sort filter-btn turnintodropdown pull-right">
        <option data-toggle="tab" value="listings" >My Listings</option>
        <option data-toggle="tab" value="likes" >My Likes</option>
        <option data-toggle="tab" value="wanted" >My Wanted</option>
    </select>
</div>
<div class="col-sm-6 col-md-7 col-xs-12 no-padding-xs profile-info">
    <div class="col-xs-2 col-sm-3 col-md-2 no-padding"> <div style="background: url('{{ url($user->thumb()) }}')" class="profile-image profile-image-large"></div></div>
    <div class="pull-left col-xs-10 col-sm-9">
        <h2 class="no-margin-top">{{ $user->username }}</h2>
        <div class="col-sm-12 col-xs-12 no-padding margin-bottom-1">
            <div class="pull-left margin-right-1"><a href="{{ url('profile/'. $user->username .'/followers') }}"><span class="black">{{ $user->follower_count }}</span> <span class="grey">Follower{{$user->follower_count != 1 ? 's' : '' }}</span></a></div>
            <div class="pull-left"><a href="{{ url('profile/'. $user->username .'/following') }}"><span class="black">{{ $user->follow_count }}</span> <span class="grey">Following</span></a></div>
        </div>
        <div class="col-sm-12 col-xs-12 no-padding margin-bottom-1">
            <div class="pull-left margin-right-1 grey"><img src="{{ url('assets/images/location_icon.png') }}" alt="location icon" class="pull-left location-icon"/>{{ $user->location }}</div>
            <div class="pull-left">
                <a href="{{ url('/profile/' . $user->username . '/reviews') }}"><input value="{{ $user->average_rating }}" type="hidden" class="rating" data-size="s" disabled></a>
            </div>
        </div>
        <div class="col-sm-12 no-padding margin-bottom-1 hidden-xs"> <a href="{{ url('account/edit') }}" class="btn sole-btn bordered-grey-btn pull-left">Edit Profile</a> </div>
    </div>
    @if ($user->bio)
        <p class="col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-3 col-xs-12 col-xs-offset-0 no-padding-xs">{{ $user->bio }}</p>
    @endif
</div>
<ul class="nav nav-tabs profile-nav-tabs col-sm-6 col-md-5 col-xs-12 pull-right hidden-xs">
    <li class="{{ $type == 'wanted' ? 'active ' : '' }}pull-right"><a href="{{ url('account/wanted') }}" class="pull-left">My Wanted</a></li>
    <li class="{{ $type == 'likes' ? 'active ' : '' }}pull-right"><a href="{{ url('account/likes') }}" class="pull-left">My Likes</a></li>
    <li class="{{ $type == 'listings' ? 'active ' : '' }}pull-right"><a href="{{ url('account/listings') }}" class="pull-left">My Listings</a></li>
</ul>
<div class="col-sm-12 hidden-xs border-bottom margin-bottom-1 margin-top-1"></div>

resources/views/pages/account/purchases.blade.php
@extends('templates.main')


@section('title', 'Purchased Shoes - Account - ')

@section('body_class') class="account_page" @stop

@section('content')
    @include('partials.review')
    @include('partials.dispute')
    <div class="white-bg col-xs-12 col-xs-offset-0 col-sm-12 col-sm-offset-0 col-md-10 col-md-offset-1 offers-info-page">
        @forelse ($shoes as $index => $shoe)
            <article class="col-sm-12 col-xs-12 bordered-box margin-bottom-1">
                @if ($index == 0)
                    <ul class="nav nav-tabs transactions-nav-tabs col-xs-12 margin-bottom-2">
                        <li class="active"><a href="{{ url('account/transactions/purchases') }}" class="pull-left">Purchased Shoes</a></li>
                        <li><a href="{{ url('account/transactions/sold') }}" class="pull-left">Sold Shoes</a></li>
                    </ul>
                @endif
                <div class="col-sm-5 col-xs-12 no-padding-xs offers-info no-padding-left">
                    <div class="border-right col-sm-12 no-padding">
                        <div class="col-sm-3 col-xs-2 no-padding"> <img src="{{ $shoe->images->first()->large() }}" class="img-responsive pull-left"/> </div>
                        <div class="col-sm-9 col-xs-10 no-padding">
                            <div class="col-sm-6 col-xs-12">
                                <p class="grey hidden-xs">Shoe</p>
                                <p><a href="{{ url('shoes/' . $shoe->slug) }}" class="black">{{ $shoe->name }}</a></p>
                            </div>
                            <div class="col-sm-6 col-xs-4 no-padding-left">
                                <div class="transactions-top-row">
                                    <p class="grey hidden-xs">Price</p>
                                    <p class="red">£{{ number_format($shoe->purchase->price, 2) }}</p>
                                </div>
                                <div>
                                    <p class="grey hidden-xs">Size</p>
                                    <p class="red">{{ $shoe->sizes->description }}</p>
                                </div>
                            </div>
                            <div class="col-xs-12 visible-xs">
                                <p>{{ $shoe->purchase->created_at->format('d/m/y') }}</p>
                            </div>
                            <a class="visible-xs pull-right collapse-btn"  aria-expanded="false" data-toggle="collapse" data-target="#info1"><img src="{{ url('assets/images/arrow_down.png') }}" alt=""></a>
                        </div>
                    </div>
                </div>
                <div id="info1" class="col-sm-7 col-xs-12 info-collapse">
                    <div class="col-sm-5 col-xs-4">
                        <div class="border-right col-sm-12 no-padding">
                            <div class="transactions-top-row">
                                <p class="grey">Sold By</p>
                                <span>
                                    <a href="{{ url('/profile/' . $shoe->sellerUser->username) }}">
                                        <div style="background-image: url('{{ $shoe->sellerUser->image }}')" class="pull-left img-circle img-circle-small img-responsive profile-img"></div>
                                    </a>
                                    <a href="{{ url('/profile/' . $shoe->sellerUser->username) }}">{{ $shoe->sellerUser->username }}</a>
                                </span>
                                <p class="red">£{{ number_format($shoe->purchase->price, 2) }}</p>
                            </div>
                            <div>
                                <p class="grey">Shipping Address</p>
                                <div>{{ $shoe->purchase->formatted_shipping_address }}</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-7 col-xs-8 no-padding">
                        <div class="col-sm-5 no-padding-left hidden-xs">
                            <p class="grey">Date and Time</p>
                            <p>
                                {{ $shoe->purchase->created_at->format('d/m/y') }}<br>
                                {{ $shoe->purchase->created_at->format('H:i') }}
                            </p>
                        </div>
                        <div class="col-sm-7 no-padding">
                            @if ($shoe->reviewByBuyer)
                                <div class="review-link btn sole-btn green-btn col-sm-12 pull-right margin-bottom no-click-btn">Reviewed</div>
                            @else
                                <a id="review-link" class="review-link btn sole-btn grey-btn col-sm-12 pull-right margin-bottom pop-up-link"
                                   data-shoe-id="{{ $shoe->id }}" data-username="{{ $shoe->sellerUser->username }}" data-image="{{ $shoe->sellerUser->image }}">Review</a>
                            @endif
                            <a href="" class="dispatch-shoe-button btn sole-btn {{ $shoe->purchase->status == 'dispatched' ? 'green-btn' : 'grey-btn' }} col-sm-12 margin-bottom pull-right no-click-btn" data-shoe-id="{{ $shoe->id }}">{{ $shoe->purchase->status == 'dispatched' ? 'Dispatched' : 'Not Dispatched' }}</a>
                            @if ($shoe->purchase->dispute)
                                <a href="" class="no-click-btn btn sole-btn green-btn col-sm-12 pull-right" data-shoe-id="{{ $shoe->id }}">{{ $shoe->purchase->dispute->disputer }} Disputed</a>
                            @else
                                <a href="" class="dispute-link btn sole-btn grey-btn col-sm-12 pull-right" data-shoe-id="{{ $shoe->id }}">Make A Dispute</a>
                            @endif
                        </div>
                    </div>
                </div>
            </article>
        @empty
            <article class="col-sm-12 bordered-box margin-bottom-1">
                <ul class="nav nav-tabs transactions-nav-tabs col-sm-6 col-md-5 col-xs-12">
                    <li class="active"><a href="{{ url('account/transactions/purchases') }}" class="pull-left">Purchased Shoes</a></li>
                    <li><a href="{{ url('account/transactions/sold') }}" class="pull-left">Sold Shoes</a></li>
                </ul>
            </article>
            @include('partials.no-results', ['text' => 'Looks like you havn\'t purchased anything yet.', 'sub_text' => 'Why don\'t you <a href="' . url('') . '">browse for shoes</a> right now? '])
        @endforelse
    </div>

    <nav>
        @include('partials.paginator', ['paginator' => $shoes])
    </nav>
@endsection

@section('footer_scripts')
    <script type="text/javascript">
        $(function() {
            $('#review-form').submit(function(e) {
                if ($('input[name=rating]').val() == 0) {
                    createStatusMessage('Please select a rating.', false);
                    e.preventDefault();
                }
                else if ($('#review-text').val().length < 10) {
                    createStatusMessage('Please enter a review that is over 10 characters in length.', false);
                    e.preventDefault();
                }

            });
        });

    </script>
@endsection

resources/views/pages/account/sold.blade.php
@extends('templates.main')

@section('title', 'Sold Shoes - Account - ')

@section('content')
    @include('partials.review-seller')
    @include('partials.dispute')
    <div class="white-bg col-xs-12 col-xs-offset-0 col-sm-12 col-sm-offset-0 col-md-10 col-md-offset-1 offers-info-page no-padding-xs">
        @forelse ($shoes as $index => $shoe)
            <article class="col-sm-12 col-xs-12 bordered-box margin-bottom-1">
                @if ($index == 0)
                    <ul class="nav nav-tabs transactions-nav-tabs col-xs-12 margin-bottom-2">
                        <li><a href="{{ url('account/transactions/purchases') }}" class="pull-left">Purchased Shoes</a></li>
                        <li class="active"><a href="{{ url('account/transactions/sold') }}" class="pull-left">Sold Shoes</a></li>
                    </ul>
                @endif
                <div class="col-sm-5 col-xs-12 no-padding-xs offers-info no-padding-left">
                    <div class="border-right col-sm-12 no-padding">
                        <div class="col-sm-3 col-xs-2 no-padding"> <img src="{{ $shoe->images->first()->large() }}" class="img-responsive pull-left"/> </div>
                        <div class="col-sm-9 col-xs-10 no-padding">
                            <div class="col-sm-6 col-xs-12">
                                <p class="grey hidden-xs">Shoe</p>
                                <p><a href="{{ url('shoes/' . $shoe->slug) }}" class="black">{{ $shoe->name }}</a></p>
                            </div>
                            <div class="col-sm-6 col-xs-4 no-padding-left">
                                <div class="transactions-top-row">
                                    <p class="grey hidden-xs">Price</p>
                                    <p class="red">£{{ number_format($shoe->purchase->price, 2) }}</p>
                                </div>
                                <div>
                                    <p class="grey hidden-xs">Size</p>
                                    <p class="red">{{ $shoe->sizes->description }}</p>
                                </div>
                            </div>
                            <div class="col-xs-12 visible-xs">
                                <p>{{ $shoe->purchase->created_at->format('d/m/y') }}</p>
                            </div>
                            <a class="visible-xs pull-right collapse-btn"  aria-expanded="false" data-toggle="collapse" data-target="#info1"><img src="{{ url('assets/images/arrow_down.png') }}" alt=""></a>
                        </div>
                    </div>
                </div>
                <div id="info1" class="col-sm-7 col-xs-12 info-collapse">
                    <div class="col-sm-5 col-xs-4">
                        <div class="border-right col-sm-12 no-padding">
                            <div class="transactions-top-row">
                                <p class="grey">Bought By</p>
                                <span>
                                    <a href="{{ url('/profile/' . $shoe->purchase->user->username) }}">
                                        <div style="background-image: url('{{ $shoe->purchase->user->image }}')" class="pull-left img-circle img-circle-small img-responsive profile-img"></div>
                                    </a>
                                    <a href="{{ url('/profile/' . $shoe->purchase->user->username) }}">{{ $shoe->purchase->user->username }}</a>
                                </span>
                                <p class="red">£{{ number_format($shoe->purchase->price, 2) }}</p>
                            </div>
                            <div>
                                <p class="grey">Shipping Address</p>
                                <div>{{ $shoe->purchase->formatted_shipping_address }}</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-7 col-xs-8 no-padding">
                        <div class="col-sm-5 no-padding-left hidden-xs">
                            <p class="grey">Date and Time</p>
                            <p>
                                {{ $shoe->purchase->created_at->format('d/m/y') }}<br>
                                {{ $shoe->purchase->created_at->format('H:i') }}
                            </p>
                        </div>
                        <div class="col-sm-7 no-padding">
                            @if ($shoe->reviewBySeller)
                                <div class="review-link btn sole-btn green-btn col-sm-12 pull-right margin-bottom no-click-btn">Reviewed</div>
                            @else
                                <a id="review-link" class="review-link btn sole-btn grey-btn col-sm-12 pull-right margin-bottom pop-up-link"
                                   data-shoe-id="{{ $shoe->id }}" data-username="{{ $shoe->purchase->user->username }}" data-image="{{ $shoe->purchase->user->image }}">Review</a>
                            @endif
                            <a href=""
                               class="dispatch-shoe-button btn sole-btn {{ $shoe->purchase->status == 'dispatched' ? 'green-btn' : 'grey-btn' }} col-sm-12 margin-bottom pull-right"
                               data-shoe-id="{{ $shoe->id }}">{{ $shoe->purchase->status == 'dispatched' ? 'Dispatched' : 'Mark as Dispatched' }}</a>
                            @if ($shoe->purchase->dispute)
                                <a href="" class="no-click-btn btn sole-btn green-btn col-sm-12 pull-right" data-shoe-id="{{ $shoe->id }}">{{ $shoe->purchase->dispute->disputer }} Disputed</a>
                            @else
                                <a href="" class="dispute-link btn sole-btn grey-btn col-sm-12 pull-right" data-shoe-id="{{ $shoe->id }}">Make A Dispute</a>
                            @endif
                        </div>
                    </div>
                </div>
            </article>
        @empty
            <article class="col-sm-12 bordered-box margin-bottom-1">
                <ul class="nav nav-tabs transactions-nav-tabs col-sm-6 col-md-5 col-xs-12">
                    <li><a href="{{ url('account/transactions/purchases') }}" class="pull-left">Purchased Shoes</a></li>
                    <li class="active"><a href="{{ url('account/transactions/sold') }}" class="pull-left">Sold Shoes</a></li>
                </ul>
            </article>
            @include('partials.no-results', ['text' => 'Looks like you\'ve not sold any shoes yet.', 'sub_text' => 'Why don\'t you  <a href="' . url('upload/shoe') . '">upload a shoe</a>?'])
        @endforelse
        <nav>
            @include('partials.paginator', ['paginator' => $shoes])
        </nav>
    </div>

@endsection

@section('footer_scripts')
    <script type="text/javascript">
        $(function() {
            $('#review-form').submit(function(e) {
                if ($('input[name=rating]').val() == 0) {
                    createStatusMessage('Please select a rating.', false);
                    e.preventDefault();
                }
                else if ($('#review-text').val().length < 10) {
                    createStatusMessage('Please enter a review that is over 10 characters in length.', false);
                    e.preventDefault();
                }

            });

           $('.dispatch-shoe-button').click(function(e) {
               e.preventDefault();

               var update = function(element, selected) {
                   if (!selected) {
                       $(element).removeClass('green-btn');
                       $(element).addClass('grey-btn');
                       $(element).text('Mark as Dispatched');
                   } else {
                       $(element).removeClass('grey-btn');
                       $(element).addClass('green-btn');
                       $(element).text('Dispatched');
                   }
               };
               var shoeId = $(this).data('shoe-id');

               update(this, !$(this).hasClass('green-btn'));

               $.post(BASE_URL + '/account/transactions/' + shoeId + '/dispatch', function(data){
                   update(this, data.shoe_status == 'dispatched');
               });
           });
        });

    </script>
@endsection